#!/bin/sh

# This script will rsync various directories to ZFS and snapshot them.
# (c) 2007 Chris Samuel

# This script is licensed under the GPL v3 license or later.
# http://www.gnu.org/copyleft/gpl.html

# First work out the datestamp to be used for all snapshots.

DATE=$(date +%Y%m%d-%H%M)

# Configuration
# Volume name
VOLNAME=/media/DR
# Subvolume name
SUBVOL=${VOLNAME}/current
# Snapshot name
SNAPNAME=${VOLNAME}/${DATE}

echo Snapshot will be labelled $DATE

if [ \! -d $SUBVOL ]; then
	echo "DR volume not mounted!"
	exit 1
fi

# Snapshot top level directories we care about.

for i in etc home; do

	echo Processing $i

	time rsync --inplace --no-whole-file --delete-excluded --exclude .beagle --exclude .bibble --exclude .googleearth --exclude .thumbnails -a /$i/ ${SUBVOL}/$i/


done

# Snapshot directories under /srv

for i in Subversion Archives backup; do

	echo Processing $i

	time rsync --inplace --delete-excluded --exclude .beagle --exclude .bibble --exclude .googleearth --exclude .thumbnails -a /srv/$i/ ${SUBVOL}/$i/

done

btrfs subvolume snapshot $SUBVOL $SNAPNAME

sync

# All done!
